services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: threads
    volumes:
      - ./path/to/local/directory:/var/lib/postgresql/data
